// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ6m_jexL7j2sUFmROhWON4oUgP1Kjda4',
    appId: '1:922744673418:web:91c740a8e21da8c6544973',
    messagingSenderId: '922744673418',
    projectId: 'aichat-fa4e3',
    authDomain: 'aichat-fa4e3.firebaseapp.com',
    storageBucket: 'aichat-fa4e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs2boLCxQvGmlzFxGWS-2wOxOQDrWjQKA',
    appId: '1:922744673418:android:aed7d75079973401544973',
    messagingSenderId: '922744673418',
    projectId: 'aichat-fa4e3',
    storageBucket: 'aichat-fa4e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcoNBIFUzNz-4h2-ASrRS0KTwARP3Ee4M',
    appId: '1:922744673418:ios:cd904b5076a88313544973',
    messagingSenderId: '922744673418',
    projectId: 'aichat-fa4e3',
    storageBucket: 'aichat-fa4e3.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcoNBIFUzNz-4h2-ASrRS0KTwARP3Ee4M',
    appId: '1:922744673418:ios:cd904b5076a88313544973',
    messagingSenderId: '922744673418',
    projectId: 'aichat-fa4e3',
    storageBucket: 'aichat-fa4e3.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ6m_jexL7j2sUFmROhWON4oUgP1Kjda4',
    appId: '1:922744673418:web:56920007e8c997e6544973',
    messagingSenderId: '922744673418',
    projectId: 'aichat-fa4e3',
    authDomain: 'aichat-fa4e3.firebaseapp.com',
    storageBucket: 'aichat-fa4e3.firebasestorage.app',
  );
}
